export const YANDEX_INITIAL_PAGE = 'YANDEX_INITIAL_PAGE'
export const YANDEX_SEARCH_RESULT = 'YANDEX_SEARCH_RESULT'
export const YANDEX_CHECKBOX_CAPTCHA = 'YANDEX_CHECKBOX_CAPTCHA'
export const YANDEX_IMAGE_CAPTCHA = 'YANDEX_IMAGE_CAPTCHA'
