export const MAIL_INITIAL_PAGE = 'MAIL_INITIAL_PAGE'
export const MAIL_SEARCH_RESULT = 'MAIL_SEARCH_RESULT'
export const MAIL_CHECKBOX_CAPTCHA = 'MAIL_CHECKBOX_CAPTCHA'
export const MAIL_IMAGE_CAPTCHA = 'MAIL_IMAGE_CAPTCHA'
